### ISSUE TITLE
training  problem

### ISSUE THREAD

**Issue by kyrietop11** [Lizhe1228/MambaDFuse#4]
作者，您好！
我在复现您的代码的过程中，按照您的要求安装了对应版本的conv2d和mamba_ssm库，并对mamba_simple.py进行了替换，但是在进行训练时，程序发生报错如下：
Traceback (most recent call last):
  File "train_MambaDFuse.py", line 260, in <module>
    main()
  File "train_MambaDFuse.py", line 194, in main
    model.optimize_parameters(current_step)
  File "/home/kyrie/MambaDFuse/models/model_plain.py", line 187, in optimize_parameters
    self.netG_forward()
  File "/home/kyrie/MambaDFuse/models/model_plain.py", line 176, in netG_forward
    self.E = self.netG(self.A, self.B)
  File "/home/kyrie/anaconda3/envs/MambaDFuse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyrie/anaconda3/envs/MambaDFuse/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/kyrie/anaconda3/envs/MambaDFuse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyrie/MambaDFuse/models/network.py", line 495, in forward
    feature1, residual_feature1, feature2, residual_feature2, h, w = self.dual_level_feature_extraction(x,y)
  File "/home/kyrie/MambaDFuse/models/network.py", line 429, in dual_level_feature_extraction
    I1,residual_I1_f = self.high_level_feature_extraction1([I1,residual_I1_f])
  File "/home/kyrie/anaconda3/envs/MambaDFuse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyrie/anaconda3/envs/MambaDFuse/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/kyrie/anaconda3/envs/MambaDFuse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyrie/MambaDFuse/models/network.py", line 137, in forward
    return (self.encoder(x),residual)
  File "/home/kyrie/anaconda3/envs/MambaDFuse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyrie/anaconda3/envs/MambaDFuse/lib/python3.8/site-packages/mamba_ssm/modules/mamba_simple.py", line 383, in forward
    out = mamba_inner_fn(
TypeError: 'NoneType' object is not callable

麻烦问一下是什么原因呢？

**Comment by songxujay** [comment]
您好，想问一下，您是怎么解决的这个关于
out = mamba_inner_fn(
TypeError: 'NoneType' object is not callable
的问题，谢谢。

**Comment by kyrietop11** [comment]
> 
[selective_scan_interface.zip](https://github.com/Lizhe1228/MambaDFuse/files/15373826/selective_scan_interface.zip)
您好，想问一下，您是怎么解决的这个关于 out = mamba_inner_fn( TypeError: 'NoneType' object is not callable 的问题，谢谢。

对虚拟环境中mamba_ssm库下的ops文件夹中的selective_scan_interface.py进行了替换

**Comment by songxujay** [comment]
十分感谢！已经运行出结果了。

**Comment by SadInSummer** [comment]
> 十分感谢！已经运行出结果了。

您好，我想问一下，这个代码中的netg和nete，也就是我要训练就必须有这两个的预训练参数？我可以把这个预训练关掉不，我现在需要修改网络来做项目，如果我不在文件夹下放这两个的预训练参数，就一直卡在加载的过程，如果我放了，则提示我确实部分预训练参数，求教，十分感谢。

**Comment by SuGuilin** [comment]
> > 
> 
> [selective_scan_interface.zip](https://github.com/Lizhe1228/MambaDFuse/files/15373826/selective_scan_interface.zip) 您好，想问一下，您是怎么解决的这个关于 out = mamba_inner_fn( TypeError: 'NoneType' object is not callable 的问题，谢谢。
> 
> 对虚拟环境中mamba_ssm库下的ops文件夹中的selective_scan_interface.py进行了替换

请问能否发一下mamba_simple.py

**Comment by Laulen** [comment]
> 非常感谢！已经运行了结果了。

Have you ever been stuck in loading optimizerG?
